name: Release

on:
  workflow_dispatch: {}
  push:
    tags:
      - v[0-9]+

jobs:  
  publish:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release
      uses: softprops/action-gh-release@v1
